### PR TITLE
Flowchart formatting options

### PR DESCRIPTION
**Pull request by bjornbm**
This patch allows to provide formatting options for a flowchart in a JSON file. See _Demo 2 with color coding (flowstate)_ at http://flowchart.js.org.

### CODE REVIEW

**Comment by bjornbm** [comment]
Any interest in this @francoislaberge?

**Comment by francoislaberge** [comment]
Hey @bjornbm. Sorry I have my Github notifications set a little aggressively. So I've been missing notifications. Fixing that now. Reviewing this now.

**Comment by francoislaberge** [comment]
Ok, so I like this idea, but I was hoping long term to come up with a unified styling approach for all of the diagram file formats. 

So I don't think this is the direction I want to take the module. Thoughts? I'm busy as hell with work, and not likely to get to that anytime soon though. So sorry to block this while also not providing a solution to wanting styling.

**Comment by bjornbm** [comment]
Thanks for taking a look and for the feedback. Very fair. My need right now is to generate styled flowcharts for which I can use my fork so you are not blocking my work. Good luck with work in the meantime!

**Pull request closed without merging**
