### PR TITLE
update js-sequence-diagrams to version 2.0.1

### PR DESCRIPTION
**Pull request by EdJoPaTo**
I updated to the newest release from [bramp/js-sequence-diagrams](//github.com/bramp/js-sequence-diagrams). I tested this very shortly. The sequence diagram I checked it with looks fine.

You should check it again because you know better what to look for. (Maybe there are some other dependencies updated that the new version of js-sequence-diagram requires in some cases?)

### CODE REVIEW

**Comment by francoislaberge** [comment]
Why update it? Are there new features?

**Comment by EdJoPaTo** [comment]
in the currently used version there are white rectangles behind the text.
In the new version the fill property of the already existing rectangles of the stakeholders are used instead. This results in a much cleaner looking svg on colored backgrounds (and smaller svg file size)

**Current Version**
old
**New Version**
new

**Comment by EdJoPaTo** [comment]
Is there a blocker? What can I do in order to complete this pr?

I would like to see it working :)

**Comment by francoislaberge** [comment]
Thanks for this! Looks much better.

**Comment by francoislaberge** [comment]
This new version is deployed:
https://github.com/francoislaberge/diagrams/releases/tag/v0.9.0

Also I updated atom-diagrams with this change: 
https://github.com/francoislaberge/atom-diagrams/releases/tag/v0.27.0

**Pull request merged**
